//! cc-protocol build script — the Rust half of the dialect toolchain
//! (dev plan Phase 0.3 `gen_rust.sh` wiring + Phase 1.1).
//!
//! 1. Stages `cc_dialect.xml` and the PINNED upstream includes
//!    (`cc-dialect/upstream/{common,standard,minimal}.xml`) into
//!    `OUT_DIR/definitions`, so `<include>` resolution uses exactly the
//!    pinned files — the same staging rule `gen_c.sh` applies for mavgen.
//! 2. Runs mavlink-bindgen on the staged set. Bindings land in
//!    `OUT_DIR/mavlink/` and are `include!`d by `src/lib.rs`; they are never
//!    vendored, so they can never drift from the XML.
//! 3. Computes `CC_DIALECT_HASH` / `CC_DIALECT_SHA256` from the raw XML bytes
//!    (same definition as `cc-dialect/hash.sh`: SHA-256, and the first 4
//!    digest bytes as a big-endian u32) into `OUT_DIR/dialect_hash.rs`.
//!    The golden round-trip test proves this value equals the C side's,
//!    because the golden CC_MISSION_CONTEXT frame embeds the C constant.

use sha2::Digest;
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    // The generated bindings carry cfg_attr gates for optional integrations
    // (serde/ts-rs/arbitrary) that this crate does not enable; declare the
    // cfg values as known so `unexpected_cfgs` stays a useful lint for OUR
    // code instead of drowning in ~2000 generated-code warnings.
    println!(
        "cargo::rustc-check-cfg=cfg(feature, values(\"serde\", \"ts-rs\", \"arbitrary\"))"
    );

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dialect_dir = manifest_dir.join("../../cc-dialect");

    // --- 1. stage the dialect + pinned includes -------------------------
    let staged = out_dir.join("definitions");
    if staged.exists() {
        fs::remove_dir_all(&staged).expect("clear staged definitions");
    }
    fs::create_dir_all(&staged).expect("create staged definitions dir");

    for (src, name) in [
        ("cc_dialect.xml", "cc_dialect.xml"),
        ("upstream/common.xml", "common.xml"),
        ("upstream/standard.xml", "standard.xml"),
        ("upstream/minimal.xml", "minimal.xml"),
    ] {
        let from = dialect_dir.join(src);
        assert!(
            from.is_file(),
            "dialect source missing: {} — is cc-dialect/ checked out next to crates/?",
            from.display()
        );
        fs::copy(&from, staged.join(name)).expect("stage dialect xml");
        println!("cargo:rerun-if-changed={}", from.display());
    }

    // --- 2. generate the bindings ---------------------------------------
    let bindings_out = out_dir.join("mavlink");
    if bindings_out.exists() {
        fs::remove_dir_all(&bindings_out).expect("clear old bindings");
    }
    fs::create_dir_all(&bindings_out).expect("create bindings dir");

    // Only cc_dialect.xml is passed explicitly: mavlink-bindgen merges the
    // <include> chain (common -> standard -> minimal, resolved from the same
    // staged directory) into that single module, so the generated
    // `dialects::cc_dialect` contains HEARTBEAT/TIMESYNC/etc. alongside the
    // CC_* messages — exactly the "one dialect" the spec (§3.1) describes.
    let result = mavlink_bindgen::generate(
        mavlink_bindgen::XmlDefinitions::Files(vec![staged.join("cc_dialect.xml")]),
        &bindings_out,
    )
    .expect("mavlink-bindgen failed on cc_dialect.xml");
    mavlink_bindgen::emit_cargo_build_messages(&result);

    // --- 3. dialect hash --------------------------------------------------
    let xml = fs::read(dialect_dir.join("cc_dialect.xml")).expect("read cc_dialect.xml");
    let digest = sha2::Sha256::digest(&xml);
    let hash32 = u32::from_be_bytes([digest[0], digest[1], digest[2], digest[3]]);
    let hex: String = digest.iter().map(|b| format!("{b:02x}")).collect();

    fs::write(
        out_dir.join("dialect_hash.rs"),
        format!(
            "// AUTOGENERATED by cc-protocol/build.rs — DO NOT EDIT.\n\
             // Source file : cc-dialect/cc_dialect.xml\n\
             // SHA-256     : {hex}\n\n\
             /// First 4 bytes of the SHA-256 of cc_dialect.xml, big-endian.\n\
             /// Carried in CC_MISSION_CONTEXT.dialect_hash (spec §7).\n\
             pub const CC_DIALECT_HASH: u32 = {hash32:#010x};\n\n\
             /// Full SHA-256 of cc_dialect.xml (hex).\n\
             pub const CC_DIALECT_SHA256: &str = \"{hex}\";\n"
        ),
    )
    .expect("write dialect_hash.rs");
}
