/* ===========================================================================
 * gen_golden.c — golden-vector generator (development plan Phase 1.2)
 *
 * Encodes one instance of EVERY CC_* message (plus HEARTBEAT and TIMESYNC,
 * which the link depends on) with fixed, documented field values, using the
 * mavgen-generated C headers — i.e. the exact encoder family the PX4 side
 * will use — and dumps the raw MAVLink 2 frames to golden_frames.bin.
 *
 * The Rust side (crates/cc-protocol/tests/golden_roundtrip.rs) parses that
 * file, asserts every field, re-encodes, and asserts byte identity. If C and
 * Rust ever disagree on wire layout or CRC_EXTRA, that test fails. This is
 * the CRC_EXTRA drift detector demanded by spec §3.1 / dev plan Phase 1.3.
 *
 * RULES
 *  - Fixed values are the contract: the Rust test mirrors them literally.
 *    Change them only together, in one commit, with the manifest regenerated.
 *  - All floats are exactly representable in binary (x.5, x.25, x.125 ...)
 *    so cross-language equality asserts are exact, never epsilon-based.
 *  - NaN fields use a pinned quiet-NaN bit pattern (0x7FC00000): the C NAN
 *    macro's payload is not pinned by the standard, and the golden bytes
 *    must be identical on every platform.
 *  - Frame order and header sequence numbers are fixed: frame index == seq
 *    (all frames are finalized on MAVLINK_COMM_0, whose tx counter starts
 *    at 0). FC-originated frames use sysid 1 / comp 1 (MAV_COMP_ID_AUTOPILOT1),
 *    CC-originated frames use sysid 1 / comp 191
 *    (MAV_COMP_ID_ONBOARD_COMPUTER), per spec §3.3.
 *  - Two deliberate edge probes at the end:
 *      frame 14: CC_EVENT whose trailing fields are zero -> exercises
 *                MAVLink 2 zero-truncation (payload shrinks on the wire);
 *      frame 15: TIMESYNC with an all-zero payload -> exercises the
 *                "payload is truncated to a minimum of 1 byte" rule.
 *  - No timestamps, hostnames, or anything non-deterministic may enter the
 *    outputs: regenerating from the same XML must be byte-identical (CI
 *    diffs the committed artifacts against a fresh regeneration).
 *
 * Outputs (written into the directory given as argv[1], default "."):
 *   golden_frames.bin    concatenated raw MAVLink 2 frames
 *   golden_manifest.txt  one line per frame:
 *                        idx offset frame_len msgid hdr_seq sysid compid
 *                        payload_len crc_extra name
 * ======================================================================== */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#include <cc_dialect/mavlink.h>
#include "dialect_hash.h"

#define GOLDEN_SYSID   1
#define COMPID_FC      MAV_COMP_ID_AUTOPILOT1       /* 1   */
#define COMPID_CC      MAV_COMP_ID_ONBOARD_COMPUTER /* 191 */

static FILE    *g_bin;
static FILE    *g_manifest;
static uint32_t g_offset;
static int      g_index;

/* Pinned quiet NaN — see RULES above. */
static float qnan_f32(void)
{
    const uint32_t bits = 0x7FC00000u;
    float f;
    memcpy(&f, &bits, sizeof f);
    return f;
}

static void emit(const mavlink_message_t *msg, const char *name)
{
    uint8_t buf[MAVLINK_MAX_PACKET_LEN];
    const uint16_t len = mavlink_msg_to_send_buffer(buf, msg);
    const mavlink_msg_entry_t *entry = mavlink_get_msg_entry(msg->msgid);

    if (entry == NULL) {
        fprintf(stderr, "gen_golden: no msg entry for id %u (%s)\n",
                (unsigned)msg->msgid, name);
        exit(1);
    }
    if (fwrite(buf, 1, len, g_bin) != len) {
        perror("gen_golden: fwrite");
        exit(1);
    }
    fprintf(g_manifest, "%d %u %u %u %u %u %u %u %u %s\n",
            g_index, g_offset, (unsigned)len, (unsigned)msg->msgid,
            (unsigned)msg->seq, (unsigned)msg->sysid, (unsigned)msg->compid,
            (unsigned)msg->len, (unsigned)entry->crc_extra, name);

    g_offset += len;
    g_index  += 1;
}

int main(int argc, char **argv)
{
    const char *outdir = (argc > 1) ? argv[1] : ".";
    char path[1024];
    mavlink_message_t msg;
    const float QNAN = qnan_f32();

    snprintf(path, sizeof path, "%s/golden_frames.bin", outdir);
    g_bin = fopen(path, "wb");
    if (!g_bin) { perror(path); return 1; }

    snprintf(path, sizeof path, "%s/golden_manifest.txt", outdir);
    g_manifest = fopen(path, "w");
    if (!g_manifest) { perror(path); return 1; }

    fprintf(g_manifest,
            "# golden_manifest.txt — AUTOGENERATED by gen_golden.c; DO NOT EDIT.\n"
            "# dialect sha256 : %s\n"
            "# dialect_hash   : 0x%08x\n"
            "# columns: idx offset frame_len msgid hdr_seq sysid compid"
            " payload_len crc_extra name\n",
            CC_DIALECT_SHA256, (unsigned)CC_DIALECT_HASH);

    /* --- frame 0: HEARTBEAT (FC) ----------------------------------------- */
    {
        mavlink_heartbeat_t p;
        memset(&p, 0, sizeof p);
        p.custom_mode     = 16909060u;              /* 0x01020304 */
        p.type            = MAV_TYPE_QUADROTOR;     /* 2  */
        p.autopilot       = MAV_AUTOPILOT_PX4;      /* 12 */
        p.base_mode       = 129u;                   /* 0x81: CUSTOM_MODE_ENABLED|SAFETY_ARMED */
        p.system_status   = MAV_STATE_ACTIVE;       /* 4  */
        p.mavlink_version = 3u;
        mavlink_msg_heartbeat_encode(GOLDEN_SYSID, COMPID_FC, &msg, &p);
        emit(&msg, "HEARTBEAT");
    }

    /* --- frame 1: TIMESYNC (FC) ------------------------------------------ */
    {
        mavlink_timesync_t p;
        memset(&p, 0, sizeof p);
        p.tc1 = 111222333444555LL;
        p.ts1 = 999888777666555LL;
        mavlink_msg_timesync_encode(GOLDEN_SYSID, COMPID_FC, &msg, &p);
        emit(&msg, "TIMESYNC");
    }

    /* --- frame 2: CC_TELEMETRY_STATE (FC) -------------------------------- */
    {
        mavlink_cc_telemetry_state_t p;
        memset(&p, 0, sizeof p);
        p.fc_timestamp_us    = 1234567890123456ULL;
        p.sequence           = 42001u;
        p.px4_boot_id        = 0xB007B007u;
        p.mission_id         = 777001u;
        p.failsafe_flags     = 0x00010203u;
        p.q[0] =  1.0f;   p.q[1] = -0.5f;  p.q[2] = 0.25f; p.q[3] = -0.125f;
        p.angular_velocity[0] = 0.125f;
        p.angular_velocity[1] = -0.25f;
        p.angular_velocity[2] = 0.5f;
        p.position_ned[0] = 10.5f;  p.position_ned[1] = -20.25f; p.position_ned[2] = -30.125f;
        p.velocity_ned[0] = 1.5f;   p.velocity_ned[1] = -2.25f;  p.velocity_ned[2] = 3.125f;
        p.heading            = 1.5f;
        p.nav_state          = 14u;
        p.arming_state       = 2u;
        p.vehicle_type       = 2u;
        p.estimator_valid    = 1u;
        p.control_mode_flags = 0xA5u;
        p.schema_version     = 1u;
        mavlink_msg_cc_telemetry_state_encode(GOLDEN_SYSID, COMPID_FC, &msg, &p);
        emit(&msg, "CC_TELEMETRY_STATE");
    }

    /* --- frame 3: CC_TELEMETRY_IMU (FC) ----------------------------------- */
    {
        mavlink_cc_telemetry_imu_t p;
        memset(&p, 0, sizeof p);
        p.fc_timestamp_us  = 1234567890123457ULL;
        p.sequence         = 42002u;
        p.clipping_count   = 7u;
        p.accel[0] = 0.5f;      p.accel[1] = -9.8125f;  p.accel[2] = 1.25f;
        p.gyro[0]  = 0.0625f;   p.gyro[1]  = -0.125f;   p.gyro[2]  = 0.25f;
        p.delta_angle[0]    = 0.03125f;
        p.delta_angle[1]    = -0.0625f;
        p.delta_angle[2]    = 0.125f;
        p.delta_velocity[0] = 0.25f;
        p.delta_velocity[1] = -0.5f;
        p.delta_velocity[2] = 0.75f;
        p.vibration_metric[0] = 1.5f;
        p.vibration_metric[1] = 2.5f;
        p.vibration_metric[2] = 3.5f;
        p.temperature      = 45.5f;
        p.schema_version   = 1u;
        mavlink_msg_cc_telemetry_imu_encode(GOLDEN_SYSID, COMPID_FC, &msg, &p);
        emit(&msg, "CC_TELEMETRY_IMU");
    }

    /* --- frame 4: CC_TELEMETRY_POWER (FC) --------------------------------- */
    {
        mavlink_cc_telemetry_power_t p;
        memset(&p, 0, sizeof p);
        p.fc_timestamp_us = 1234567890123458ULL;
        p.sequence        = 42003u;
        p.voltage         = 22.5f;
        p.current         = 15.25f;
        p.power           = 343.125f;
        p.consumed_mah    = 1250.5f;
        p.remaining       = 0.75f;
        p.temperature     = QNAN;   /* "NaN if unknown" contract, spec §6 */
        p.cell_count      = 6u;
        p.warning         = 1u;
        p.connected       = 1u;
        p.schema_version  = 1u;
        mavlink_msg_cc_telemetry_power_encode(GOLDEN_SYSID, COMPID_FC, &msg, &p);
        emit(&msg, "CC_TELEMETRY_POWER");
    }

    /* --- frame 5: CC_TELEMETRY_GPS (FC) ------------------------------------ */
    {
        mavlink_cc_telemetry_gps_t p;
        memset(&p, 0, sizeof p);
        p.fc_timestamp_us   = 1234567890123459ULL;
        p.sequence          = 42004u;
        p.lat               = 473977420;   /* 47.3977420 degE7 */
        p.lon               = 85455940;    /*  8.5455940 degE7 */
        p.alt               = 488000;      /* 488 m AMSL, mm   */
        p.eph               = 1.25f;
        p.epv               = 2.5f;
        p.ground_speed      = 12.5f;
        p.heading           = -1.5f;
        p.noise_per_ms      = 55u;
        p.jamming_indicator = 33u;
        p.fix_type          = 3u;          /* 3D fix */
        p.satellites_used   = 17u;
        p.schema_version    = 1u;
        mavlink_msg_cc_telemetry_gps_encode(GOLDEN_SYSID, COMPID_FC, &msg, &p);
        emit(&msg, "CC_TELEMETRY_GPS");
    }

    /* --- frame 6: CC_TELEMETRY_ESTIMATOR (FC) ------------------------------ */
    {
        mavlink_cc_telemetry_estimator_t p;
        memset(&p, 0, sizeof p);
        p.fc_timestamp_us        = 1234567890123460ULL;
        p.sequence               = 42005u;
        p.status_flags           = 0x00FF00FFu;
        p.innovation_check_flags = 0x0F0Fu;
        p.solution_status_flags  = 0x0355u;
        p.velocity_test_ratio    = 0.25f;
        p.position_test_ratio    = 0.5f;
        p.height_test_ratio      = 0.125f;
        p.mag_test_ratio         = 0.75f;
        p.airspeed_test_ratio    = QNAN;   /* not applicable on a quadrotor */
        p.schema_version         = 1u;
        mavlink_msg_cc_telemetry_estimator_encode(GOLDEN_SYSID, COMPID_FC, &msg, &p);
        emit(&msg, "CC_TELEMETRY_ESTIMATOR");
    }

    /* --- frame 7: CC_TELEMETRY_ACTUATOR (FC) ------------------------------- */
    {
        mavlink_cc_telemetry_actuator_t p;
        memset(&p, 0, sizeof p);
        p.fc_timestamp_us = 1234567890123461ULL;
        p.sequence        = 42006u;
        p.actuator_output[0] = 0.1015625f;   /* 13/128 */
        p.actuator_output[1] = 0.203125f;    /* 13/64  */
        p.actuator_output[2] = 0.3046875f;   /* 39/128 */
        p.actuator_output[3] = 0.40625f;     /* 13/32  */
        p.actuator_output[4] = QNAN;         /* unused slots are NaN, spec §6 */
        p.actuator_output[5] = QNAN;
        p.actuator_output[6] = QNAN;
        p.actuator_output[7] = QNAN;
        p.motor_count     = 4u;
        p.schema_version  = 1u;
        mavlink_msg_cc_telemetry_actuator_encode(GOLDEN_SYSID, COMPID_FC, &msg, &p);
        emit(&msg, "CC_TELEMETRY_ACTUATOR");
    }

    /* --- frame 8: CC_EVENT (FC) -------------------------------------------- */
    {
        mavlink_cc_event_t p;
        memset(&p, 0, sizeof p);
        p.fc_timestamp_us = 1234567890123462ULL;
        p.sequence        = 42007u;
        p.event_id        = 0x00CC0001u;
        p.argument0       = 111u;
        p.argument1       = 222u;
        p.severity        = CC_SEVERITY_WARN;      /* 1 */
        p.subsystem       = CC_SUBSYS_VIBRATION;   /* 3 */
        p.schema_version  = 1u;
        mavlink_msg_cc_event_encode(GOLDEN_SYSID, COMPID_FC, &msg, &p);
        emit(&msg, "CC_EVENT");
    }

    /* --- frame 9: CC_SAFETY_STATUS (FC) ------------------------------------ */
    {
        mavlink_cc_safety_status_t p;
        memset(&p, 0, sizeof p);
        p.fc_timestamp_us      = 1234567890123463ULL;
        p.last_report_sequence = 88005u;   /* acks frame 10's report */
        p.active_health_flags  = 1029u;    /* BATTERY|VIBRATION|TIMESYNC = 1|4|1024 */
        p.report_age_ms        = 150u;
        p.missed_reports       = 3u;
        p.companion_state      = CC_STATE_WARN;        /* 2 */
        p.action_taken         = CC_ACTION_WARN_ONLY;  /* 1 */
        p.reject_reason        = CC_REJECT_NONE;       /* 0 */
        p.schema_version       = 1u;
        mavlink_msg_cc_safety_status_encode(GOLDEN_SYSID, COMPID_FC, &msg, &p);
        emit(&msg, "CC_SAFETY_STATUS");
    }

    /* --- frame 10: CC_HEALTH_REPORT (CC, comp 191) -------------------------- */
    {
        mavlink_cc_health_report_t p;
        memset(&p, 0, sizeof p);
        p.companion_timestamp_us = 987654321098765ULL;
        p.sequence               = 88005u;
        p.mission_id             = 777001u;
        p.companion_boot_id      = 0xCC0CC001u;
        p.health_flags           = 1029u;
        p.detail_code            = 0x0BADu;
        p.link_rtt_ms            = 12u;
        p.telemetry_age_ms       = 40u;
        p.companion_loop_ms      = 5u;
        p.dropped_rx_count       = 2u;
        p.severity               = CC_SEVERITY_WARN;     /* 1  */
        p.recommended_action     = CC_ACTION_WARN_ONLY;  /* 1  */
        p.confidence_percent     = 87u;
        p.schema_version         = 1u;
        mavlink_msg_cc_health_report_encode(GOLDEN_SYSID, COMPID_CC, &msg, &p);
        emit(&msg, "CC_HEALTH_REPORT");
    }

    /* --- frame 11: CC_AI_DIAGNOSTIC (CC, comp 191) --------------------------- */
    {
        mavlink_cc_ai_diagnostic_t p;
        memset(&p, 0, sizeof p);
        p.companion_timestamp_us = 987654321098766ULL;
        p.sequence               = 91001u;
        p.value                  = 3.375f;
        p.limit                  = 2.5f;
        p.detail_code            = 0x0BADu;
        p.subsystem              = CC_SUBSYS_BATTERY;   /* 1 */
        p.severity               = CC_SEVERITY_WARN;    /* 1 */
        p.confidence_percent     = 87u;
        p.schema_version         = 1u;
        mavlink_msg_cc_ai_diagnostic_encode(GOLDEN_SYSID, COMPID_CC, &msg, &p);
        emit(&msg, "CC_AI_DIAGNOSTIC");
    }

    /* --- frame 12: CC_MISSION_CONTEXT (CC, comp 191) -------------------------- */
    {
        mavlink_cc_mission_context_t p;
        memset(&p, 0, sizeof p);
        p.mission_id     = 777001u;
        p.cc_boot_id     = 0xCC0CC001u;
        p.vehicle_id     = 4242u;
        /* The REAL dialect hash: proves hash.sh (C side) and cc-protocol's
         * build.rs (Rust side) computed the same value, end to end. */
        p.dialect_hash   = CC_DIALECT_HASH;
        memcpy(p.sw_version, "cc-golden-0.1.0", 15);  /* NUL padded to 24 */
        p.schema_version = 1u;
        mavlink_msg_cc_mission_context_encode(GOLDEN_SYSID, COMPID_CC, &msg, &p);
        emit(&msg, "CC_MISSION_CONTEXT");
    }

    /* --- frame 13: CC_LOG_CONTROL (CC, comp 191) ------------------------------ */
    {
        mavlink_cc_log_control_t p;
        memset(&p, 0, sizeof p);
        p.companion_timestamp_us = 987654321098767ULL;
        p.sequence               = 91002u;
        p.requested_profile      = CC_PROFILE_DEBUG;   /* 3 */
        p.schema_version         = 1u;
        mavlink_msg_cc_log_control_encode(GOLDEN_SYSID, COMPID_CC, &msg, &p);
        emit(&msg, "CC_LOG_CONTROL");
    }

    /* --- frame 14: CC_EVENT zero-truncation probe (FC) ------------------------ */
    /* Trailing fields deliberately zero: argument1, severity, subsystem and
     * schema_version are all 0, and argument0 = 222 = 0xDE 00 00 00, so the
     * wire payload truncates mid-argument0 (27 -> 17 bytes). The Rust side
     * must zero-fill on decode and re-truncate identically on encode. */
    {
        mavlink_cc_event_t p;
        memset(&p, 0, sizeof p);
        p.fc_timestamp_us = 1234567890123999ULL;
        p.sequence        = 42999u;
        p.event_id        = 0x00CC0002u;
        p.argument0       = 222u;
        p.argument1       = 0u;
        p.severity        = CC_SEVERITY_OK;    /* 0 */
        p.subsystem       = CC_SUBSYS_NONE;    /* 0 */
        p.schema_version  = 0u;
        mavlink_msg_cc_event_encode(GOLDEN_SYSID, COMPID_FC, &msg, &p);
        emit(&msg, "CC_EVENT_TRUNCATION_PROBE");
    }

    /* --- frame 15: TIMESYNC minimum-payload probe (FC) ------------------------ */
    /* All-zero payload: MAVLink 2 truncates to a minimum of ONE byte, never
     * zero. The C and Rust implementations must agree on that rule. */
    {
        mavlink_timesync_t p;
        memset(&p, 0, sizeof p);
        mavlink_msg_timesync_encode(GOLDEN_SYSID, COMPID_FC, &msg, &p);
        emit(&msg, "TIMESYNC_MIN_PAYLOAD_PROBE");
    }

    fclose(g_bin);
    fclose(g_manifest);
    printf("gen_golden: wrote %d frames, %u bytes -> %s/golden_frames.bin\n",
           g_index, g_offset, outdir);
    return 0;
}
