#!/usr/bin/env bash
# ============================================================================
# hash.sh — dialect_hash generator (development plan Phase 0.3)
#
# Computes the stable hash of cc_dialect.xml and emits it as constants for
# both languages:
#
#   generated/dialect_hash.h    C header (PX4 side + golden-vector generator)
#   generated/dialect_hash.rs   Rust mirror (informational / PX4-parity file;
#                               cc-protocol's build.rs recomputes the same
#                               value independently at build time, and the
#                               golden round-trip test proves all copies agree)
#
# Definition (see docs/phase0_dialect_toolchain.md):
#   CC_DIALECT_SHA256  = SHA-256 over the raw bytes of cc_dialect.xml
#   CC_DIALECT_HASH    = first 4 bytes of the digest read as a big-endian
#                        u32 (i.e. the first 8 hex characters of the digest)
#
# CC_DIALECT_HASH is the value carried on the wire in
# CC_MISSION_CONTEXT.dialect_hash (spec §7 session handshake).
#
# Any byte change to the XML — including comments — changes the hash. That is
# intentional: the hash identifies the exact file both bindings were generated
# from; it is not a semantic fingerprint.
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
XML="$SCRIPT_DIR/cc_dialect.xml"
OUT_DIR="$SCRIPT_DIR/generated"

[[ -f "$XML" ]] || { echo "error: $XML not found" >&2; exit 1; }
mkdir -p "$OUT_DIR"

# SHA-256 of the raw XML bytes (macOS ships shasum, most Linux sha256sum).
if command -v shasum >/dev/null 2>&1; then
    SHA="$(shasum -a 256 "$XML" | awk '{print $1}')"
elif command -v sha256sum >/dev/null 2>&1; then
    SHA="$(sha256sum "$XML" | awk '{print $1}')"
else
    echo "error: need shasum or sha256sum" >&2; exit 1
fi

HASH32="0x${SHA:0:8}"

cat > "$OUT_DIR/dialect_hash.h" <<EOF
// AUTOGENERATED by cc-dialect/hash.sh — DO NOT EDIT.
// Source file : cc_dialect.xml
// SHA-256     : $SHA
//
// CC_DIALECT_HASH = first 4 bytes of the SHA-256 digest as a big-endian u32.
// Carried in CC_MISSION_CONTEXT.dialect_hash; both ends must agree or the
// mission handshake is refused (spec §7, §11 "Schema mismatch").
#pragma once
#include <stdint.h>

#define CC_DIALECT_SHA256 "$SHA"
#define CC_DIALECT_HASH   ((uint32_t)${HASH32}u)
EOF

cat > "$OUT_DIR/dialect_hash.rs" <<EOF
// AUTOGENERATED by cc-dialect/hash.sh — DO NOT EDIT.
// Source file : cc_dialect.xml
// SHA-256     : $SHA
//
// NOTE: crates/cc-protocol/build.rs computes these same constants
// independently from the XML at every build; cc-protocol's test suite
// asserts this committed copy and the build-time value are identical.

/// First 4 bytes of the SHA-256 of cc_dialect.xml, big-endian.
/// Carried in CC_MISSION_CONTEXT.dialect_hash.
pub const CC_DIALECT_HASH: u32 = $HASH32;

/// Full SHA-256 of cc_dialect.xml (hex).
pub const CC_DIALECT_SHA256: &str = "$SHA";
EOF

echo "dialect sha256 : $SHA"
echo "dialect_hash   : $HASH32"
echo "wrote          : generated/dialect_hash.h, generated/dialect_hash.rs"
